sudo: false
dist: xenial
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
jobs:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'

install:
  - python -m pip install -U pip
  - python -m pip install -U numpy
  - python -m pip install -U nose coverage codecov

script:
  - nosetests --with-coverage --cover-package=emcee -sv

after_success:
  - codecov
